insert into channels_tg values('https://t.me/A4omg');                    
insert into channels_tg values('https://t.me/aesthetics_of_theworld');   
insert into channels_tg values('https://t.me/akashevarova');             
insert into channels_tg values('https://t.me/America_Inside');           
insert into channels_tg values('https://t.me/Architecture2021');         
insert into channels_tg values('https://t.me/archivarius_dz');           
insert into channels_tg values('https://t.me/asia_pekin_tokyo');         
insert into channels_tg values('https://t.me/banksta');                  
insert into channels_tg values('https://t.me/batyapple');                
insert into channels_tg values('https://t.me/bazabazon');                
insert into channels_tg values('https://t.me/bbbreaking');               
insert into channels_tg values('https://t.me/beingamerican');            
insert into channels_tg values('https://t.me/bizsovety');                
insert into channels_tg values('https://t.me/bloodysx');                 
insert into channels_tg values('https://t.me/borodylia0803');            
insert into channels_tg values('https://t.me/breakingmash');             
insert into channels_tg values('https://t.me/chatzvz');                  
insert into channels_tg values('https://t.me/Crypto_Stoicism');          
insert into channels_tg values('https://t.me/dimsmirnov175');            
insert into channels_tg values('https://t.me/ecobabyykt');               
insert into channels_tg values('https://t.me/economikal');               
insert into channels_tg values('https://t.me/edisonfamilia');            
insert into channels_tg values('https://t.me/epoddubny');                
insert into channels_tg values('https://t.me/Fit4lifeRu');               
insert into channels_tg values('https://t.me/from_japan');               
insert into channels_tg values('https://t.me/genshindropchat');          
insert into channels_tg values('https://t.me/genshix_chat');             
insert into channels_tg values('https://t.me/genshix_wish');             
insert into channels_tg values('https://t.me/geografiyatg');             
insert into channels_tg values('https://t.me/getkit');                   
insert into channels_tg values('https://t.me/gomennassai');              
insert into channels_tg values('https://t.me/gosuslugi');                
insert into channels_tg values('https://t.me/hacks_excel');              
insert into channels_tg values('https://t.me/holmogortalks');            
insert into channels_tg values('https://t.me/hunter_deals');             
insert into channels_tg values('https://t.me/iikhuchat');                
insert into channels_tg values('https://t.me/imnotbozhena');             
insert into channels_tg values('https://t.me/instasamkafuckyou');        
insert into channels_tg values('https://t.me/kas_brows_hab');            
insert into channels_tg values('https://t.me/Knitted_clothes');          
insert into channels_tg values('https://t.me/kornilov1968');             
insert into channels_tg values('https://t.me/krispotupchik');            
insert into channels_tg values('https://t.me/kruginapole');              
insert into channels_tg values('https://t.me/LearnEnglishRus');          
insert into channels_tg values('https://t.me/lemonfortea');              
insert into channels_tg values('https://t.me/lentachold');               
insert into channels_tg values('https://t.me/lifeyt');                   
insert into channels_tg values('https://t.me/litvintm');                 
insert into channels_tg values('https://t.me/livingworldlive');          
insert into channels_tg values('https://t.me/lobaev_vlad');              
insert into channels_tg values('https://t.me/lost_in_japan');            
insert into channels_tg values('https://t.me/maslennikovliga');          
insert into channels_tg values('https://t.me/matchtv_chat');             
insert into channels_tg values('https://t.me/meduzalive');               
insert into channels_tg values('https://t.me/medvedev_telegram');        
insert into channels_tg values('https://t.me/minaevlife');               
insert into channels_tg values('https://t.me/minobrnaukiofficial');      
insert into channels_tg values('https://t.me/mintsifry');                
insert into channels_tg values('https://t.me/miraculolb');               
insert into channels_tg values('https://t.me/moscowach');                
insert into channels_tg values('https://t.me/moscowmap');                
insert into channels_tg values('https://t.me/moskvatayanchishelonlar');  
insert into channels_tg values('https://t.me/mozhemobyasnit');           
insert into channels_tg values('https://t.me/mrs_druzhinina');           
insert into channels_tg values('https://t.me/muremora78');               
insert into channels_tg values('https://t.me/musicmsk1');                
insert into channels_tg values('https://t.me/My_Own_Time');              
insert into channels_tg values('https://t.me/nashturist');               
insert into channels_tg values('https://t.me/nemorgenshtern');           
insert into channels_tg values('https://t.me/nevzorovtv');               
insert into channels_tg values('https://t.me/nevzorovtvchat');           
insert into channels_tg values('https://t.me/olegtsarov');               
insert into channels_tg values('https://t.me/OneTwoTrip');               
insert into channels_tg values('https://t.me/oper_goblin');              
insert into channels_tg values('https://t.me/ostorozhno_novosti');       
insert into channels_tg values('https://t.me/outciv');                   
insert into channels_tg values('https://t.me/pdmnews');                  
insert into channels_tg values('https://t.me/piarchatVZC');              
insert into channels_tg values('https://t.me/piarrolock');               
insert into channels_tg values('https://t.me/pravdadirty');              
insert into channels_tg values('https://t.me/prbezposhady');             
insert into channels_tg values('https://t.me/ranarod');                  
insert into channels_tg values('https://t.me/rbc_news');                 
insert into channels_tg values('https://t.me/readovchat');               
insert into channels_tg values('https://t.me/readovkanews');             
insert into channels_tg values('https://t.me/redakciya_channel');        
insert into channels_tg values('https://t.me/rhymestg');                 
insert into channels_tg values('https://t.me/rian_ru');                  
insert into channels_tg values('https://t.me/RobloxXO');                 
insert into channels_tg values('https://t.me/rt_russian');               
insert into channels_tg values('https://t.me/ru2chnews');                
insert into channels_tg values('https://t.me/ru2ch_news');               
insert into channels_tg values('https://t.me/rusbrief');                 
insert into channels_tg values('https://t.me/russica2');                 
insert into channels_tg values('https://t.me/sammyfam');                 
insert into channels_tg values('https://t.me/sashakots');                
insert into channels_tg values('https://t.me/shot_shot');                
insert into channels_tg values('https://t.me/siberian716');              
insert into channels_tg values('https://t.me/Sladkov_plus');             
insert into channels_tg values('https://t.me/SonOfMonarchy');            
insert into channels_tg values('https://t.me/sport');                    
insert into channels_tg values('https://t.me/sportsru');                 
insert into channels_tg values('https://t.me/ssigny');                   
insert into channels_tg values('https://t.me/star7k77');                 
insert into channels_tg values('https://t.me/strelkovii');               
insert into channels_tg values('https://t.me/tass_agency');              
insert into channels_tg values('https://t.me/tikandelaki');              
insert into channels_tg values('https://t.me/travelyut_turizm');         
insert into channels_tg values('https://t.me/tv360');                    
insert into channels_tg values('https://t.me/TWIYS');                    
insert into channels_tg values('https://t.me/uranews');                  
insert into channels_tg values('https://t.me/varlamov');                 
insert into channels_tg values('https://t.me/varlamov_news');            
insert into channels_tg values('https://t.me/VillaEdelweissMontenegro'); 
insert into channels_tg values('https://t.me/vladivostok1978');          
insert into channels_tg values('https://t.me/vladtodaySL');              
insert into channels_tg values('https://t.me/VTurisme');                 
insert into channels_tg values('https://t.me/warfakes');                 
insert into channels_tg values('https://t.me/wargonzo');                 
insert into channels_tg values('https://t.me/wbofficialchat');           
insert into channels_tg values('https://t.me/yurydud');                  
insert into channels_tg values('https://t.me/zabroshenworld');           
insert into channels_tg values('https://t.me/zakharprilepin');           
insert into channels_tg values('https://t.me/zanfizika');
insert into groups_vk values(-205590702,  'https://vk.com/dfilm');                       
insert into groups_vk values(-200254840,  'https://vk.com/public200254840');             
insert into groups_vk values(-147845620,  'https://vk.com/vkmusic');                     
insert into groups_vk values(-135209264,  'https://vk.com/bot_maxim');                   
insert into groups_vk values(-123915905,  'https://vk.com/films');                       
insert into groups_vk values(-113071474,  'https://vk.com/kinohd');                      
insert into groups_vk values(-109198561,  'https://vk.com/afishamsk1');                  
insert into groups_vk values(-91050183,  'https://vk.com/dayvinchik');                  
insert into groups_vk values(-79483347,  'https://vk.com/incredible0');                 
insert into groups_vk values(-71729358,  'https://vk.com/styd.pozor');                  
insert into groups_vk values(-66678575,  'https://vk.com/ovsyanochan');                 
insert into groups_vk values(-65662695,  'https://vk.com/cosec');                       
insert into groups_vk values(-61009220,  'https://vk.com/russia.travel.official');      
insert into groups_vk values(-58170807,  'https://vk.com/kino_kaif');                   
insert into groups_vk values(-57876954,  'https://vk.com/vinevinevine');                
insert into groups_vk values(-57846937,  'https://vk.com/mudakoff');                    
insert into groups_vk values(-56106344,  'https://vk.com/pn6');                         
insert into groups_vk values(-55662720,  'https://vk.com/psyxov');                      
insert into groups_vk values(-48963397,  'https://vk.com/learningrussianwithrussians'); 
insert into groups_vk values(-48946342,  'https://vk.com/i.cook');                      
insert into groups_vk values(-48512305,  'https://vk.com/tnt');                         
insert into groups_vk values(-48319873,  'https://vk.com/i.kino');                      
insert into groups_vk values(-46466345,  'https://vk.com/contact_fun');                 
insert into groups_vk values(-46117626,  'https://vk.com/prostovkusno_food');           
insert into groups_vk values(-45745333,  'https://vk.com/4ch');                         
insert into groups_vk values(-45703770,  'https://vk.com/vkmuz');                       
insert into groups_vk values(-45595714,  'https://vk.com/academyofman');                
insert into groups_vk values(-45588871,  'https://vk.com/poet_omar');                   
insert into groups_vk values(-45441631,  'https://vk.com/smeyaka');                     
insert into groups_vk values(-45064245,  'https://vk.com/be.beauty');                   
insert into groups_vk values(-45045130,  'https://vk.com/club45045130');                
insert into groups_vk values(-43879004,  'https://vk.com/sh.cook');                     
insert into groups_vk values(-43776215,  'https://vk.com/iwantyou');                    
insert into groups_vk values(-43215063,  'https://vk.com/kinomania');                   
insert into groups_vk values(-40835481,  'https://vk.com/tophumor');                    
insert into groups_vk values(-40567146,  'https://vk.com/lhack');                       
insert into groups_vk values(-40553536,  'https://vk.com/kinom');                       
insert into groups_vk values(-40498005,  'https://vk.com/psy.people');                  
insert into groups_vk values(-40335272,  'https://vk.com/movie_pab');                   
insert into groups_vk values(-40316705,  'https://vk.com/rt_russian');                  
insert into groups_vk values(-39728801,  'https://vk.com/9o_6o_9o');                    
insert into groups_vk values(-39410028,  'https://vk.com/o_ptimist');                   
insert into groups_vk values(-39081980,  'https://vk.com/leprum');                      
insert into groups_vk values(-39009769,  'https://vk.com/cook_good');                   
insert into groups_vk values(-38683579,  'https://vk.com/1poetry');                     
insert into groups_vk values(-36184135,  'https://vk.com/i_des');                       
insert into groups_vk values(-36164349,  'https://vk.com/s_arcazm');                    
insert into groups_vk values(-36008740,  'https://vk.com/i_want_love_dream');           
insert into groups_vk values(-35983383,  'https://vk.com/plmusic');                     
insert into groups_vk values(-35061290,  'https://vk.com/e_goist');                     
insert into groups_vk values(-34757875,  'https://vk.com/be.women');                    
insert into groups_vk values(-34491673,  'https://vk.com/black_humor');                 
insert into groups_vk values(-34384434,  'https://vk.com/mzk');                         
insert into groups_vk values(-34118551,  'https://vk.com/scifacts');                    
insert into groups_vk values(-33769500,  'https://vk.com/theworthyfilms');              
insert into groups_vk values(-33159467,  'https://vk.com/smechno_do_boli');             
insert into groups_vk values(-32432151,  'https://vk.com/ilove');                       
insert into groups_vk values(-32194285,  'https://vk.com/foodrumedia');                 
insert into groups_vk values(-31976785,  'https://vk.com/science_technology');          
insert into groups_vk values(-31836774,  'https://vk.com/oroom');                       
insert into groups_vk values(-30318830,  'https://vk.com/lo_horoscope');                
insert into groups_vk values(-30179569,  'https://vk.com/fucking_humor');               
insert into groups_vk values(-30022666,  'https://vk.com/lepragram');                   
insert into groups_vk values(-29686754,  'https://vk.com/woman.blog');                  
insert into groups_vk values(-29559271,  'https://vk.com/sci');                         
insert into groups_vk values(-29246653,  'https://vk.com/evil_incorparate');            
insert into groups_vk values(-28905875,  'https://vk.com/rhymes');                      
insert into groups_vk values(-28890647,  'https://vk.com/fotomagic_su');                
insert into groups_vk values(-28761941,  'https://vk.com/ishok');                       
insert into groups_vk values(-28627911,  'https://vk.com/40kg');                        
insert into groups_vk values(-28477986,  'https://vk.com/ne.poverish');                 
insert into groups_vk values(-28293246,  'https://vk.com/vk.just.love');                
insert into groups_vk values(-28261265,  'https://vk.com/sarkazmcorp');                 
insert into groups_vk values(-27895931,  'https://vk.com/exclusive_muzic');             
insert into groups_vk values(-26750264,  'https://vk.com/xfilm');                       
insert into groups_vk values(-26669118,  'https://vk.com/vk.krasota');                  
insert into groups_vk values(-26419239,  'https://vk.com/ifun');                        
insert into groups_vk values(-26062647,  'https://vk.com/kate_mobile');                 
insert into groups_vk values(-26030283,  'https://vk.com/agil_vk');                     
insert into groups_vk values(-25554967,  'https://vk.com/smsin');                       
insert into groups_vk values(-25346844,  'https://vk.com/v5inf');                       
insert into groups_vk values(-24713873,  'https://vk.com/v5umm');                       
insert into groups_vk values(-23830580,  'https://vk.com/un_horoscope');                
insert into groups_vk values(-23433159,  'https://vk.com/trahninormalnost1');           
insert into groups_vk values(-23245066,  'https://vk.com/womanruse');                   
insert into groups_vk values(-23243883,  'https://vk.com/topds');                       
insert into groups_vk values(-23064236,  'https://vk.com/ilikes');                      
insert into groups_vk values(-22822305,  'https://vk.com/vk');                          
insert into groups_vk values(-22798006,  'https://vk.com/kino_mania');                  
insert into groups_vk values(-22741624,  'https://vk.com/humour.page');                 
insert into groups_vk values(-22222333,  'https://vk.com/anekdot');                     
insert into groups_vk values(-19799369,  'https://vk.com/da_side');                     
insert into groups_vk values(-18464856,  'https://vk.com/vpovare');                     
insert into groups_vk values(-17711662,  'https://vk.com/vprikole');                    
insert into groups_vk values(-14785431,  'https://vk.com/kinoz');                       
insert into groups_vk values(-12648877,  'https://vk.com/beginenglish_ru');             
insert into groups_vk values(-12382740,  'https://vk.com/fuck_humor');                  
insert into groups_vk values(-6136139,  'https://vk.com/vk.fact');                     
insert into groups_vk values(-4916277,  'https://vk.com/club4916277');                 
insert into groups_vk values(-460389,  'https://vk.com/borsch');                      
insert into groups_vk values(-19043,  'https://vk.com/europaplus');                  
insert into groups_vk values(-1959,  'https://vk.com/record');     
